interactions = {
    MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T],
    MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T],
    OPU[A:C][C:F][N:F][P:L][F:O][J:Q][A:S],
    ONU[S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N]}

Todas mandatory:
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N]}
Una optional:
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[A:C]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[C:F]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[N:F]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[P:L]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[F:O]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[J:Q]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],OPU[A:S]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[S:D]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[A:H]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[S:H]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[A:I]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[C:I]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][J:O][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[L:K]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][S:Q][D:R][T:R][D:S][S:I][N:L][I:N],ONU[J:O]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][D:R][T:R][D:S][S:I][N:L][I:N],ONU[S:Q]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][T:R][D:S][S:I][N:L][I:N],ONU[D:R]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][D:S][S:I][N:L][I:N],ONU[T:R]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][S:I][N:L][I:N],ONU[D:S]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][N:L][I:N],ONU[S:I]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][I:N],ONU[N:L]}
interactions = {MPU[A:A][A:B][B:C][B:D][C:D][B:E][B:F][E:F][J:F][F:G][N:G][F:H][L:H][F:I][H:I][L:J][Q:J][K:K][K:L][M:M][M:N][L:P][F:R][R:S][S:S][J:T][A:C][C:F][N:F][P:L][F:O][J:Q][A:S],MNU[D:A][H:B][H:C][H:D][H:E][H:F][I:F][J:G][Q:G][B:I][J:I][O:I][F:J][N:J][H:L][N:M][F:P][J:P][R:P][P:R][E:T][G:T][S:T][S:D][A:H][S:H][A:I][C:I][L:K][J:O][S:Q][D:R][T:R][D:S][S:I][N:L],ONU[I:N]}
